name: Weekly Ruby Script Runner

on:
  push:
    branches:
      - category
  schedule:
    - cron: '0 0 * * 0' # Runs every weekend 

jobs:
  run-scripts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.1

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.4

      - name: Install mechanize gem
        run: |
          gem install mechanize

      - name: Run scripts with retry
        run: |
          retry_count=0
          max_retries=3
          exit_code=1  # Initialize exit_code to 1 (failure)

          while [ $retry_count -lt $max_retries ]; do
            # Run t.rb
            ruby seek/t.rb
            exit_code=$?
            if [ $exit_code -ne 0 ]; then
              echo "t.rb failed with exit code $exit_code, retrying..."
              retry_count=$((retry_count + 1))
              continue
            fi

            # Run tk.rb
            ruby seek/tk.rb
            exit_code=$?
            if [ $exit_code -ne 0 ]; then
              echo "tk.rb failed with exit code $exit_code, retrying..."
              retry_count=$((retry_count + 1))
              continue
            fi

            # Run tf.rb
            ruby seek/tf.rb
            exit_code=$?
            if [ $exit_code -ne 0 ]; then
              echo "tf.rb failed with exit code $exit_code, retrying..."
              retry_count=$((retry_count + 1))
              continue
            fi

            # Run new.rb
            ruby seek/new.rb
            exit_code=$?
            if [ $exit_code -eq 0 ]; then
              echo "new.rb succeeded."
              break
            elif [ $exit_code -eq 1 ]; then
              echo "new.rb failed with exit code 1, waiting for 30 seconds before retrying..."
              sleep 30
            else
              echo "new.rb failed with exit code $exit_code, retrying..."
            fi

            retry_count=$((retry_count + 1))
          done

          if [ $exit_code -ne 0 ]; then
            echo "new.rb failed after $max_retries attempts."
            exit $exit_code  # Exit with the last exit code
          fi